### PR TITLE
Sort Bookmarks in reverse bible order

### PR DESCRIPTION
**Pull request by agrogers**
This fails with the following error (x24). I tested the reverse sort (adding a minus sign to the existing sort) and it seemed to work fine. I dont know why a new sort option on an existing column wants a new column. I couldnt find how to create one to resolve this issue.

The problem i caused by the change in db/src/main/java/net/bible/android/database/bookmarks/BookmarkEntities.kt

`D:\git\and-bible-v5\db\build\tmp\kapt3\stubs\debug\net\bible\android\database\bookmarks\BookmarkDao.java:9: error: The columns returned by the query does not have the fields [new] in net.bible.android.database.bookmarks.BookmarkEntities.BibleBookmarkWithNotes even though they are annotated as non-null or primitive. Columns returned by the query: [kjvOrdinalStart,kjvOrdinalEnd,ordinalStart,ordinalEnd,v11n,playbackSettings,id,createdAt,book,startOffset,endOffset,primaryLabelId,lastUpdatedOn,wholeVerse,type,notes]
    public abstract java.util.List<net.bible.android.database.bookmarks.BookmarkEntities.BibleBookmarkWithNotes> searchAllBookmarksImpl(@org.jetbrains.annotations.NotNull`

### CODE REVIEW

**Comment by tuomas2** [comment]
It builds fine. Just build it second time after fail and it's working. It is some precompiling related issue.

**Comment by agrogers** [comment]
Oh, really? I will try again.

**Comment by agrogers** [comment]
I think this is working now.

**Comment by tuomas2** [comment]
(note: better to merge only current-stable branch towards your branch, develop is not where things happen currently. develop is for the next major release, but I'm taking smaller stuff now to current-stable prod version directly)

**Comment by agrogers** [comment]
Oh, yeah, I will try to remember that.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Pull request merged**
