### PR TITLE
Added extra options to the Share/Copy form

### PR DESCRIPTION
**Pull request by agrogers**
Added:
- Hide the Bible reference completely
- Hide the version name
- Hide the ellipsis for selected text
- Changed 'Show full verses' to 'Show selected text only'. This was needed to provide an indented option for the ellipsis and also because I think it is a little clearer what it does. There was at least one support ticket where someone didnt realise that was possible.
- New strings were needed

Closes: 
#1371 
#1151

image

### CODE REVIEW

**Comment by agrogers** [comment]
The failed check was this. I don't think that has anything to do with me.

```
net.bible.android.control.page.window.WindowControlTest > testGetMinimisedWindows FAILED
    kotlin.io.FileAlreadyExistsException: /tmp/robolectric-Method_testGetMinimisedWindows15316638377118530453/net.bible.android.activity-dataDir/databases/andBibleDatabase.db -> /tmp/robolectric-Method_testGetMinimisedWindows15316638377118530453/net.bible.android.activity-dataDir/files/database_backups/dbBackup-0-20211206-103025.db: The destination file already exists.
```

**Comment by tuomas2** [comment]
> Added string version_name for this to be implemented 
from #1151

**Comment by tuomas2** [comment]
Oh, this is PR! nice! Will take a look soon...

**Comment by tuomas2** [comment]
Tests failing

**Comment by agrogers** [comment]
Yes, but it doesn't seem to be a test related to anything I did. I mention
that in a comment.

**Comment by tuomas2** [comment]
weird, need to check

**Comment by agrogers** [comment]
Added some extra functionality. 
image

All the tests passed this time... but I didn't make any changes that should have fixed them.

**Comment by agrogers** [comment]
Closes #1974

**Comment by tuomas2** [comment]
- [x] Bug: Show quotes gives quotation mark in weird place (when fixing, please create test for this too)

image

-> looks like this is current behavior too, and .. not sure if it would make sense to put after first verse number either

**Comment by tuomas2** [comment]
I think this would benefit from better series of unit tests. So many options added, but only 1 test added. Other than that, it looks good and (probably) works (short testing ok).

**Comment by agrogers** [comment]
What's weird about the quotes?

**Comment by tuomas2** [comment]
If you are nice, you could create some more tests later on (especially if bugs are found), but I can merge this now.

**Comment by tuomas2** [comment]
> What's weird about the quotes?

never mind, see edited comment (now hidden)

**Comment by agrogers** [comment]
Sure thing

**Pull request merged**
