### PR TITLE
Improve 3.3 error report

### PR DESCRIPTION
**Pull request by timbze**
Add webview and sqlite versions to error report in 3.3

### CODE REVIEW

**Comment by tuomas2** [comment]
What motivates this?

**Comment by timbze** [comment]
In case 3.3 would get another update, it would be easier to get which webview version the user has.

The .gitignore is because when I switch to 3.3 branch it always shows lots of files that are ignored in 4.0

I was thinking of also doing a PR for automatic db restore (the backed up version from 3.3) if user wants to downgrade, but not sure that I'll have time for that.

**Comment by timbze** [comment]
But according to test it actually looks like this is not working, so I'll have to check a bit more first.

**Comment by tuomas2** [comment]
How would it work? What would be benefit over the current downgrade path?

**Comment by timbze** [comment]
> How would it work? What would be benefit over the current downgrade path?

That would make it possible to install 3.3 over 4.0 and automatically get downgraded. Instead of doing migration, app would check db before Room accesses it, and automatically restore the 3.3 backup file (before starting app essentially).

**Comment by tuomas2** [comment]
Android prevents downgrades. 4.0 needs always to be uninstalled first.

**Comment by timbze** [comment]
> Android prevents downgrades. 4.0 needs always to be uninstalled first.

Oh you're right. Good to know

**Pull request closed without merging**
