### PR TITLE
Feature/discrete mode

### PR DESCRIPTION
**Pull request by tuomas2**
- App name & icon change from settings
- settings also for calculator "smoke app": toggle to enable and setting to adjust pin code

Adapted this calculator: https://github.com/eloyzone/android-calculator

Related: #178 #1609

### CODE REVIEW

**Comment by tuomas2** [comment]
rhino library adds 316k overhead, could do without probably...

**Comment by tuomas2** [comment]
develop: 8276kB
this branch: 8552kB
diff: 276kB

**Comment by tuomas2** [comment]
Settings:

image

**Comment by tuomas2** [comment]
Launcher:

image

**Comment by tuomas2** [comment]
Calculator: 

image

**Comment by tuomas2** [comment]
splash spinner:

image

**Comment by tuomas2** [comment]
Will receive comments and fix issues later, but merging so that alpha testing can start.

@agrogers perhaps you could have ideas for settings screen icons?

**Comment by agrogers** [comment]
Coool! I am looking forward to trying that. I dont need it but I think it
is great to have. Well done.


___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Pull request merged**
