### PR TITLE
Normalize references to Strong's Concordance

### PR DESCRIPTION
**Pull request by alerque**
James Strong was a person and the concordance title is a possessive based on his name.

### CODE REVIEW

**Comment by alerque** [comment]
I noticed while trying to clean up the Turkish translation of these that the source strings were somewhat inconsistent.

**Comment by tuomas2** [comment]
We are using british english accent in Transifex for minor corrections for english translation so that transifex does not invalidate all related translations. 

I will make the fix there (if it's not already fixed).

**Comment by alerque** [comment]
Hmm, interesting arrangement. I can see not wanting no do too much invalidation, but if what I saw people doing in TR is any indication, the inconsistent source strings may be causing even worse translations. I don't know how widespread that will be in this case, but maybe I'll look through a few other languages and see if I can make sense of anything along those lines.

BTW, wouldn't the lead up to a major new release be the *least disruptive* time to fine tune source strings?

**Comment by tuomas2** [comment]
> BTW, wouldn't the lead up to a major new release be the _least disruptive_ time to fine tune source strings?

In principle yes, but not at this stage (less than 3 weeks to release) :-)

**Comment by alerque** [comment]
Okay, I wasn't sure what the timeline was. Personally my interest was more in having consistent sources to translate *from* than the English app experience, but of course I have different priorities here ;-) If you don't want to merge this I understand, but maybe I'll keep the branch around for other potential source text issues I run across and you or whoever can choose between cherry picking stuff to apply to sources, saving some bits to apply later at a more convenient time in the life cycle, discarding stuff you don't want at all, or using a temporary work around vis-à-vis the British shindig.

**Comment by tuomas2** [comment]
Fixed in transifex

**Pull request closed without merging**
