### PR TITLE
Custom repositories

### LINKED ISSUE #39: Add a way to add custom document repositories
Hello. It should be nice to have the ability to add other repos than the hardcoded ones.

Updates from @tuomas2:
 - Show SWORD MRL (master repository list) repositories automatically.

### PR DESCRIPTION
**Pull request by tuomas2**
Closes #39 

TODO:

- [x] Help texts / dialogs
- [x] try to seek manifest if repo root is given
- [x] Support "standard" Sword repository root as spec (generate manifest)
- [ ] Validate manifest URLs (that are valid HTTPS...)
- [x] Prevent duplicates (repository name should be unique)

### CODE REVIEW

**Comment by tuomas2** [comment]
image

image

image

image

**Comment by tuomas2** [comment]
image

**Comment by tuomas2** [comment]
Wiki: https://github.com/AndBible/and-bible/wiki/Custom-repositories

**Comment by agrogers** [comment]
Looks good. I will try it out.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Anyone willing to set up an external repository with some modules? Maybe @bvahedy ?

**Comment by agrogers** [comment]
Should this work?
https://awv.tenoutoften.org/AndBible/
This folder has a 'packages' folder inside with a single zip file (esv.zip) with nt.bzs, nt.bzv, nt.bzz etc inside it)

**Comment by tuomas2** [comment]
Minimally, if you add mods.d.tar.gz there it should work.

**Comment by tuomas2** [comment]
See this for example:
https://github.com/AndBible/data/tree/master/andbible/beta

(here zip folder corresponds to "packages" folder, so this one would not qualify without manifest file)

**Comment by tuomas2** [comment]
also your zip file is not following the sword module directory structure either. check other mod zip files for example.

**Comment by bvahedy** [comment]
> Anyone willing to set up an external repository with some modules? Maybe @bvahedy ?

What Andrew has would work,  I can move some of my modules in there, but I would need write access to upload. Also,  are we allowed to make ESV available?

**Comment by tuomas2** [comment]
> > Anyone willing to set up an external repository with some modules? Maybe @bvahedy ?
> 
> What Andrew has would work, I can move some of my modules in there, but I would need write access to upload. Also, are we allowed to make ESV available?

Please do not make ESV available. We can't control what others do, but we (AndBible, and AndBible developers) should not release any copyrighted modules without permission.

**Comment by tuomas2** [comment]
> > Anyone willing to set up an external repository with some modules? Maybe @bvahedy ?
> 
> What Andrew has would work, I can move some of my modules in there, but I would need write access to upload. Also, are we allowed to make ESV available?

Github pages allows anyone to make a repository easily via a normal Git repository: https://pages.github.com/.

**Pull request merged**
