### PR TITLE
Set the active window button to the same colour as the toolbar

### PR DESCRIPTION
**Pull request by agrogers**
This replaces the previous PR which I will try to delete now.

### CODE REVIEW

**Comment by tuomas2** [comment]
Allright let's try..

**Comment by tuomas2** [comment]
Colors are very confusing in restore window area.
https://youtu.be/Y5a2xBLV_Go

**Comment by tuomas2** [comment]
will revert now. You can create a new pull request, reverting the revert commit  (c737a5aa26838cfb2ab055b23250d243837ea57b) and then improving this further.

**Comment by agrogers** [comment]
I am not sure what the problem is.  the active window takes the toolbar
color (replaces blue outline) . The dark buttons are are visible windows
(same as before). And light buttons are not visible windows (same as
before). Only change is that the blue outline is replaced with a solid
colour.

Thinking about it now just changing the outline colour would be more
aesthetically pleasing than the blue outline which looks out of place with
new colours.

Mine looks both clear and beautiful 😇

**Comment by agrogers** [comment]
I am not sure what the problem is. the active window takes the toolbar color (replaces blue outline) . The dark buttons are are visible windows (same as before). And light buttons are not visible windows (same as before). Only change is that the blue outline is replaced with a solid colour. Thinking about it now just changing the outline colour would be more aesthetically pleasing than the blue outline which looks out of place with new colours. Mine looks both clear and beautiful 😇

**Comment by tuomas2** [comment]
Hmm maybe I need to give it another try with more than just 2 windows

**Comment by timbze** [comment]
Another option might be to just change the border color, or even make it a bit thicker.

**Comment by agrogers** [comment]
Yeah, if the border matched the workspace color it would look nice. My
original reason for the change was because I have accidentally changed the
document for the wrong window soooo many times. That always bugs me. Making
the active window button more identifiable was my aim and this helps but I
still sometimes change the document for the wrong window.

My suggestion to change the way the toolbar buttons operate will mostly
solve that problem for me.

**Comment by agrogers** [comment]
@tuomas2, is this merged into the develop branch? It looks like it is but I can't find it in develop.

**Comment by tuomas2** [comment]
> @tuomas2, is this merged into the develop branch? It looks like it is but I can't find it in develop.

I reverted it as I said here:
> will revert now. You can create a new pull request, reverting the revert commit (https://github.com/AndBible/and-bible/commit/c737a5aa26838cfb2ab055b23250d243837ea57b) and then improving this further.

But I will now revert my revert so it will get another try.

**Comment by tuomas2** [comment]
with default grey workspace color there is no active window indication now.

**Comment by agrogers** [comment]
OK, i read 'give it another try' differently. 

I will have a look at the grey worksapce color.

**Comment by tuomas2** [comment]
What about reverting to old version but making border significantly thicker:

image

It match more with the style of active window highlight (blue corner markers)

**Comment by tuomas2** [comment]
Implemented this in 78a9828996d9251a0d1187b5774b7746c702279f (but it's still open for discussion / different solutions)

**Pull request merged**
