### PR TITLE
Multiple underline highlighting done 'perfectly'

### PR DESCRIPTION
**Pull request by agrogers**
This is underline highlighting done almost perfectly :) I am not using a lot more underline highlights because of the original reason I asked you to implement them -they are less intrusive. Now i can have multiple ones visible and still not be intrusive at all. Its pretty cool.

The below is not how I use them in practice. It is just to show what it can do.

image

One of the advantages is that the lines coexist with the Strongs underlining.

image

And at different font sizes...

image

image

They overlap when the line spacing gets below about 1.3. It's not an issue to my mind. It still looks and functions fine. And if people want to cramp their text that is the price to pay.

image

### CODE REVIEW

**Comment by tuomas2** [comment]
you can also run npm run lint to see errors.

**Comment by agrogers** [comment]
OK, i will try.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
I see this but sadly it doesn't help me.....

Run npm run lint:ci
  npm run lint:ci
  shell: /usr/bin/bash -e {0}

> ***@***.*** lint:ci
/home/runner/work/and-bible/and-bible/app/bibleview-js
> vue-cli-service lint --no-fix --no-color > lint-results.txt

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ***@***.*** lint:ci: `vue-cli-service lint --no-fix
--no-color > lint-results.txt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ***@***.*** lint:ci script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-07T14_35_31_460Z-debug.log
Error: Process completed with exit code 1.


And this....

Annotations
1 error and 1 warning
build
<https://github.com/AndBible/and-bible/runs/3269688838?check_suite_focus=true>
Process completed with exit code 1.
build
<https://github.com/AndBible/and-bible/runs/3269688838?check_suite_focus=true>
No files were found with the provided path:
app/bibleview-js/test-report.html. No artifacts will be uploaded.
___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
https://github.com/AndBible/and-bible/pull/1556

**Comment by tuomas2** [comment]
Trying this now (build from #1556). Initially seem to work well! Good work!

**Comment by agrogers** [comment]
Thanks. I should have added some checks when it is trying to show more bookmarks than is possible. It doesnt really matter I dont think because anything beyond 100% is hidden. I can add those checks if you end up leaving my code in. But my code is definitely not 'perfect'. So maybe you will want to rework.

Also, I never did work out how to find that linting problem.

**Comment by tuomas2** [comment]
If there are partial highlights within a verse, it will show underlines differently, but that's ok (I guess) and just the way this works. I don't believe there's easy way to get around it.

image

**Comment by agrogers** [comment]
Yes, that is the same as the previous underline method. It only happens when there are selection highlights which is what I think you meant.

I would be OK with those numbers etc not being underlined. But then they would be underlined in whole verse bookmarks and not at all in verses with a selection highlight.

**Comment by tuomas2** [comment]
Yes this difference is due to code that makes rendering full-verse bookmark ranges much faster and simpler.

**Comment by agrogers** [comment]
Yes, I thought so.

**Comment by tuomas2** [comment]
Merged #1556. You can improve code as new PRs if you like. Added some tests in bookmarks.spec.js ("verseHighlight tests"), so if you edit code, you can also add some tests.

**Pull request closed without merging**
