### PR TITLE
Feature/#1609 discrete variant preparation

### PR DESCRIPTION
**Pull request by uniqueid001**
This sets up the initial structure for a variant with entirely different branding:  it defines a "flavorDimension" of 'appearance', with two flavors: 'standard' and 'discrete', and instructs Android Studio to recognize the 'standard' flavor as the default variant.  It currently placeholder logos and app names.

This could be merged into 'develop', or it could be kept on its own branch until it is more complete and actually useful.

### CODE REVIEW

**Comment by agrogers** [comment]
Looks good.

**Comment by tuomas2** [comment]
What is the motivation for doing this?

**Comment by uniqueid001** [comment]
> What is the motivation for doing this?

The discussion on #1609 talked about creating a variant of andbible which was not-so-obviously Christian.  This is just the first "baby step" towards that goal.  Since I have some experience with flavors and variants I started here to prepare the opportunity for others to contribute.
If you want, I think it makes a lot of sense to keep this on a separate branch in the and-bible project instead of merging it into the develop branch.  Then subsequent contributions can request merging into that branch while the feature is in progress.

**Comment by tuomas2** [comment]
> > What is the motivation for doing this?
> 
> The discussion on #1609 talked about creating a variant of andbible which was not-so-obviously Christian. This is just the first "baby step" towards that goal. Since I have some experience with flavors and variants I started here to prepare the opportunity for others to contribute. If you want, I think it makes a lot of sense to keep this on a separate branch in the and-bible project instead of merging it into the develop branch. Then subsequent contributions can request merging into that branch while the feature is in progress.

I see. I think it's okay to merge this. I'm not yet sure which approach to take for #1609. I'm still in hopes that we could implement it such a way that we don't need to have a variant.

**Comment by tuomas2** [comment]
Now there's conflict because I just merged another PR from you.. :-)

**Comment by tuomas2** [comment]
Can you fix the conflicts? I could merge otherwise

**Comment by uniqueid001** [comment]
Yes, I am working on it.

**Pull request merged**
