### PR TITLE
Improve CI release text and add release notes

### PR DESCRIPTION
**Pull request by timbze**
Addresses #730:
- for production and beta releases, description for apk release could be taken from fastlane changelog txt automatically
- title for beta / production releases should be "Release 3.3.381" or "Release 3.3.381-beta"

### CODE REVIEW

**Comment by tuomas2** [comment]
What if changelog txt does not exist? I think it would be better it would not crash then either.

**Comment by tuomas2** [comment]
It might be cool if, in beta releases, there would be list of commit messages (truncated, if long), or even better, list of issues closed.

**Comment by timbze** [comment]
> What if changelog txt does not exist? I think it would be better it would not crash then either.

It does not crash.
This runs first (creates empty file). And if the file is empty we get the same result as now (i.e. just showing latest commit msg)
`cat > ./RELEASENOTES.txt`

If the changelog file exists, the empty file is replaced with the changelog file and the Github release body gets that text

**Comment by timbze** [comment]
> What if changelog txt does not exist? I think it would be better it would not crash then either.

Changed code now to only run `cp` when the file exists

**Pull request merged**
