### PR TITLE
Ctrl + c copies text with correct formatting

### PR DESCRIPTION
**Pull request by timbze**
Related #2622 

One issue still needs to be solved.

If I select text manually on AB startup (before verse has been clicked), and then press Ctrl + c, it uses system copy instead of my implemented "share copy". This is because `AmbiguousSelection` has not yet been loaded (which listens to Ctrl + c press).

However, once I click a verse and `AmbiguousSelection` loads, I can close the modal, select text manually and press Ctrl + c and the text is copied using my "share copy". I am not sure why, because it looks like `setupDocumentEventListener` in utils does (or should) removeEventListener on `onUnmounted`.

I would like for ctrl + c to always use my "share copy", is that correct thinking for user UX? Commentaries and genbooks etc will still just have regular system copy.

If ctrl + c should always use "share copy" even for manually selected Bible text, should the Ctrl + c listener be somewhere else than in `AmbiguousSelection` component?

### CODE REVIEW

**Comment by tuomas2** [comment]
Are you planning to work on the remaining issue or waiting for help?

**Comment by timbze** [comment]
> I would like for ctrl + c to always use my "share copy", is that correct thinking for user UX? Commentaries and genbooks etc will still just have regular system copy.
> 
> If ctrl + c should always use "share copy" even for manually selected Bible text, should the Ctrl + c listener be somewhere else than in `AmbiguousSelection` component?

I'm waiting for a response to this then I want to finish it

**Comment by tuomas2** [comment]
> > I would like for ctrl + c to always use my "share copy", is that correct thinking for user UX? Commentaries and genbooks etc will still just have regular system copy.
> > If ctrl + c should always use "share copy" even for manually selected Bible text, should the Ctrl + c listener be somewhere else than in `AmbiguousSelection` component?
> 
> I'm waiting for a response to this then I want to finish it

In which context is CTRL+C supposed to work exactly? I though it is only when AmbiguousSelection component is visible.

**Comment by timbze** [comment]
> In which context is CTRL+C supposed to work exactly? I though it is only when AmbiguousSelection component is visible.

I would like for it to also work when selecting text with mouse. In this case AmbigiousSelection component does not show.

**Comment by tuomas2** [comment]
> > In which context is CTRL+C supposed to work exactly? I though it is only when AmbiguousSelection component is visible.
> 
> I would like for it to also work when selecting text with mouse. In this case AmbigiousSelection component does not show.

It needs separate implementation I think. It's different to work with AmbiguousSelection than general selection.

**Comment by timbze** [comment]
> It needs separate implementation I think. It's different to work with AmbiguousSelection than general selection.

Ok, I know how I could do that, but I was a bit confused why the listener in AmbiguousSelection does not get unregistered when AmbigiousSelection is unloaded. Do you know why?

**Comment by tuomas2** [comment]
> > It needs separate implementation I think. It's different to work with AmbiguousSelection than general selection.
> 
> Ok, I know how I could do that, but I was a bit confused why the listener in AmbiguousSelection does not get unregistered when AmbigiousSelection is unloaded. Do you know why?

AmbiguousSelection is loaded all the time, just UI part hidden most of the time (see BibleView.vue where it is loaded).

**Comment by timbze** [comment]
I think this is done now

**Review by tuomas2 — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
