### PR TITLE
Drop use of deprecated buildDir

### PR DESCRIPTION
**Pull request by MikAoJk**
**Describe the pull request content**
Drop use of deprecated buildDir
Benefits not using deprecated methods
Possible negative side effects? none

**Screenshots**
N/A

### CODE REVIEW

**Comment by tuomas2** [comment]
Why did you close the PR?

**Comment by MikAoJk** [comment]
closed it, because it seemed like no one was looking at it

**Comment by tuomas2** [comment]
I will (noticed it and it is in my project board)  but my time is limited and need to prioritize heavily.

**Comment by tuomas2** [comment]
merged manually now

**Pull request closed without merging**
