### PR TITLE
Complete all missing Turkish translations

### PR DESCRIPTION
**Pull request by alerque**
c.f. #2684

### CODE REVIEW

**Comment by alerque** [comment]
I'm headed out for something else and have no idea when I'll be back at it. Obviously I tackled the two smaller resource files before digging into the big one! Feel free to poke if I forget about this. I'm leaving it as draft because I do plan to work on the strings.xml file too, but also feel free to merge and feed this back into Transifex at any time.

One disadvantage of working this way is some of the meta data like character count limits is not enforced. I tried to look up that info on the ones I thought might have restrictions, but one thing we probably do want to do is round-trip these through Transifex and check the diff. If that cuts some of them off I can go back and fix those.

**Comment by tuomas2** [comment]
There are not many strings that have enforcements in use; I think only some google play related strings have limits.

**Comment by tuomas2** [comment]
I'll leave this PR open until you are finished or when we are releasing. Or if you want to test translations in a beta build, just ping me to merge it and release in next beta build.

**Comment by alerque** [comment]
This should now bring Turkish up to 100% translated. The strings here are of various quality, some of them could use some copy editing and all of them could use some consistency checking. I noticed the existing strings had several major inconsistencies and did not try to resolve those when translating new strings.

I think I'd like to see this first pass merged earlier rather than later, then round-tripped into Transifex (where other reviewers are more likely to be able to chip in than they are here) and then back to the code so we can make sure the import/export doesn't surface any errors like too-long strings, mismatched placeholders, etc. I'll try to take another pass at editing everything again later, but seeing it in a beta might be useful too.

**Comment by alerque** [comment]
I discovered the API and CLI tooling is something I can use too, so I've taken care of the round-tripping into Transifex, so the issues with that are already fixed in this branch and Transifex is up to date.

It would still be nice to merge this PR for the Git history even though they would come through later in a regular translations pull anyway.

**Comment by tuomas2** [comment]
So you have enough permissions to upload you translations to transifex? 

I can merge and trigger a build for you so you can test it.

**Comment by tuomas2** [comment]
Test build will appear here after CI is finishing: https://github.com/AndBible/and-bible/releases/tag/build-736-turkish-translation

**Comment by alerque** [comment]
> So you have enough permissions to upload you translations to transifex?

Yes. I was a little bit surprised too, but I guess because I'm marked as the coordinator for the Turkish team I have special privs. Or maybe anybody on the team can use the API, I don't know. In any case I was pleasantly surprised by how smoothly it went, a few oddities notwithstanding.

**Comment by tuomas2** [comment]
> > So you have enough permissions to upload you translations to transifex?
> 
> Yes. I was a little bit surprised too, but I guess because I'm marked as the coordinator for the Turkish team I have special privs. Or maybe anybody on the team can use the API, I don't know. In any case I was pleasantly surprised by how smoothly it went, a few oddities notwithstanding.

I believe it is because you are coordinator. Normal translators can (as far as I know) only translate untranslated strings (or those that they have translated themselves).

**Comment by tuomas2** [comment]
So everything is pushed there so it's fine to overwrite these files in git next time when I pull?

**Comment by tuomas2** [comment]
Big thanks BTW for updating turkish :-)

**Comment by alerque** [comment]
> So everything is pushed there so it's fine to overwrite these files in git next time when I pull?

Yes, exactly, I've already round-tripped all three resources, the online copies are the freshest again so other contributors can jump in there, and you can feel free to pull & force pull from Transifex again at any time. I may do some more work directly on the Git side but I can make sure I freshen the resources from Transifex before I start next time so I don't clobber anyone's contributions.

Thanks for facilitating this.

**Pull request merged**
