### PR TITLE
feat: adds monochromatic & rounded icons

### LINKED ISSUE #3053: [Feature] Themed / Monochromatic App icon support
**Is your feature request related to a problem? Please describe.**
The app's icon looks out of place when using themed icons (although it is very pretty)

**Describe the solution you'd like**
Implement a monochromatic version of the icon when it is enabled by the user.

**Describe alternatives you've considered**
Leave the app icon as-is

**Additional context**
[Developer Reference](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

### PR DESCRIPTION
**Pull request by nandgator**
## Describe the pull request content

Adds monochromatic & rounded icons.

Ref: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

## Screenshots

| Normal | Monochromatic |
| --- | --- |
signal-2023-11-23-200628_003 | signal-2023-11-23-200628_002 |

Resolves https://github.com/AndBible/and-bible/issues/3053

> Not sure why, normal icons are a bit blurred. Will debug. Any ideas?

### CODE REVIEW

**Comment by tuomas2** [comment]
Related: #3053

**Comment by tuomas2** [comment]
Looks good. How does user choose which one to use? Is it launcher app setting?

**Comment by tuomas2** [comment]
Fish should not have white in the tail crossing?

**Comment by nandgator** [comment]
> Related: #3053

Oh cool, I didn't check issues, my bad.

> Fish should not have white in the tail crossing?

As yes, I'm using https://penpot.app to intersect paths, let me see what I can do.

> Looks good. How does user choose which one to use? Is it launcher app setting?

On Samsung phones: `Settings > Wallpaper and style > Colour Pallet`

**Comment by nandgator** [comment]
Updated: 

signal-2023-11-23-233713_003

signal-2023-11-23-233713_002

**Comment by nandgator** [comment]
Finally!

| Normal | Monochromatic |
| --- | --- |
| signal-2023-11-24-180610_002 | signal-2023-11-24-180610_003 |

Uses vector based adaptive icons.

**Comment by tuomas2** [comment]
Thanks for doing this!
Merging for beta testing. Will revert if any issue arise.

**Comment by tuomas2** [comment]
Oops, this was against develop.... I will cherry-pick this to current-stable branch.

**Pull request merged**
