### PR TITLE
add additional info to Dictionary Word picker

### PR DESCRIPTION
**Pull request by RuggMatt**
**Describe the pull request content**
This just adds some additional info to the Hebrew/Greek word picker 
image

I am not sure if this is the best way to extract the info. It works for the AndBible Greek and Hebrew dictionaries, but nothing else. I am not sure if how I look up the additional info is the best way to go about it, or if there is a more general way to query for the `entryFree` info.

**Screenshots**
If applicable, add screenshots to help explain your pull request.

### CODE REVIEW

**Comment by agrogers** [comment]
Screenshot looks good to me. How does it look with normal dictionaries like Smiths or Easton?

**Comment by RuggMatt** [comment]
@agrogers other dictionaries already have the name as the key.
image

Strongs Greek and Hebrew just had the Strongs number. Now it also shows the related word next to it.

**Comment by agrogers** [comment]
Ah, i get it now.

I would also like to show the first few lines of the actual dictionary
entry in the list. There have been more than a few occasions where that
would have been all i needed.

But I think that will really slow down retrieval.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by RuggMatt** [comment]
@agrogers I did some testing and did not find any performance issues with retrieval. 
image

**Comment by tuomas2** [comment]
Looks good to me, merging

**Comment by tuomas2** [comment]
As always, unit testing would be nice, but I'm assuming you'll fix the bugs if there will be any related :-)

**Pull request merged**
