### PR TITLE
More icon additions and changes

### PR DESCRIPTION
**Pull request by agrogers**

### CODE REVIEW

**Comment by tuomas2** [comment]
As it looks like you are still working on this, let's change it to "drawft" pull request. You can change status back when it is ready to be merged.

**Comment by agrogers** [comment]
Ah, that's what 'draft' means. I will use that in the future. Thanks.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
> Removed the margin and padding around the outside of the edit control. The original CSS applied to all modals so needed to get around that with an extra class property.
> 
> image

I tried to revert this edit box change in this pull request but left it in the original pull request. Maybe i have done the wrong thing. Sorry!

**Comment by agrogers** [comment]
I have made a mess with this one. Reverted something i shouldn't  have I think. So I will close this request and see if i can make another that  is cleaner.

**Pull request closed without merging**
