### PR TITLE
Improve navigation with reading plans

### LINKED ISSUE #1719: Clicking the Passage button on a 'done' reading plan item takes me to the next item
I accidentally pushed the Done button and so went back to that item using the selector. But now when I push the passage button it just takes me to the next day. What I expected was that the button would take me to the passage.

### LINKED ISSUE #1722: Setting 'Start Date' only works every second time
This action only seems to work on every second attempt.

### LINKED ISSUE #1773: Reading plan: user unable to go back to book
https://support.andbible.org/scp/tickets.php?id=840

> In my reading plan I am unable to go to the book as it takes me back to the beginning when I select it.

### PR DESCRIPTION
**Pull request by timbze**
Fixes #1773
Fixes #1719
Fixes #1722

### CODE REVIEW

**Comment by timbze** [comment]
Should this PR be toward `current-stable`?

**Comment by tuomas2** [comment]
develop is still the branch from where I do production deployments. That is going to change at some point (probably soonish), but I will let you know when it happens.

**Comment by tuomas2** [comment]
Looks good. 
BUT. 
I did not test this. 
Hope this is well tested.
Please test properly before thursday 4.11 when this goes to production.

**Comment by timbze** [comment]
I did test quite a bit, but can do some more, also maybe someone from  @AndBible/developers wants to help test yet too.

Main changes in this PR are how navigation works (reading plan) when going to another day, another reading plan, go to passage, press back, etc.

**Pull request merged**
