### PR TITLE
Kotlinization

### LINKED ISSUE #2263: Convert rest Java files to Kotlin
Noticed that we do not have a lot of them any more, so better to convert the rest.

### PR DESCRIPTION
**Pull request by tuomas2**
Closes #2263

### CODE REVIEW

**Comment by agrogers** [comment]
I am guessing they were all automated changes, yes? What did you use?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
mostly but several hours of manual work too

**Comment by tuomas2** [comment]
used Android studios java to kotlin

**Comment by tuomas2** [comment]
will fix tests next time

**Comment by agrogers** [comment]
I use that too but often it doesn't work and I don't know what to do then 😁

**Comment by tuomas2** [comment]
> I use that too but often it doesn't work and I don't know what to do then 😁

just need to go through the code and see that it makes sense and works 😊

**Comment by agrogers** [comment]
... you mean go through the code and know stuff that I don't yet know :D

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Pull request merged**
