### PR TITLE
#265 Allow user to click checkmark in reading plan to complete chapter

### LINKED ISSUE #265: Reading Plan; allow user to tap checkmark to complete chapter
In the Reading Plan page, you can click the Passage button then press back, and the check turns green. I am reading the Bible in my paperback Bible, but using the app to keep track of my plan, so it would be easier for me to just press the check and have it completed.
**I already wrote the code** for myself, very simple fix, but I don't know if this is something that you want in the app as a feature. I will add it if you would like.

### PR DESCRIPTION
**Pull request by timbze**
Here's the pull request for the reading plan "checkmark click" feature.

Closes #265

### CODE REVIEW

**Comment by tuomas2** [comment]
@timbze added info about which issue ticket this closes (please add this info in the future yourself)

**Comment by tuomas2** [comment]
Should you also implement un-tick after second click if someone accidentally ticks it?

**Comment by timbze** [comment]
> Should you also implement un-tick after second click if someone accidentally ticks it?

I think it's a good idea. Will do soon.

**Comment by tuomas2** [comment]
> I think it's a good idea. Will do soon.

@timbze you can do this in separate pull request. Merging this so that I can do the kotlinization of readingplan code as we agreed.

**Pull request merged**
