### PR TITLE
Updated icons and overlay icon

### PR DESCRIPTION
**Pull request by agrogers**
image

### CODE REVIEW

**Comment by agrogers** [comment]
Sorry if these should have been split out into different pull requests. I need a primer on how best to submit these ideas. I am fairly sure you will want to keep the icons. I am happy with most of them. The changes to the way the workspace sync displays might not meet your approval. Give it a chance though. You might like it :)  It looks nice I think.

image

image

**Comment by timbze** [comment]
Appreciate all your hard work on beautifying AB, Andrew!

In this PR, I don't like the "feet" icon for footnotes. That's my opinion and if others like it then go for it 😊

**Comment by agrogers** [comment]
I went for the shoe, not the feet. I thought the feet was going too far
;-)  Open to suggestions. Send me something you like and I will try to
find/make something similar.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
Though I'm not a pro at finding icons, something like these look decent to me...

- https://iconify.design/icon-sets/carbon/notebook-reference.html
- https://iconify.design/icon-sets/codicon/references.html

**Comment by tuomas2** [comment]
lint found some errors that need fixing

**Comment by agrogers** [comment]
I saw some errors messages but didn't know what caused them nor where to
look to find out what caused them. What should I do next time?

**Pull request merged**
