### PR TITLE
Highlight the words in the search results

### PR DESCRIPTION
**Pull request by agrogers**
It handles multiple words and the '*' operator. It doesn't handle phrases or '?' yet. And it is not tested. Let me know if it is heading in the right direction and I (or you) can finish it off later.

image

image

### CODE REVIEW

**Comment by timbze** [comment]
I'm guessing it won't handle strongs search either? (haven't looked at code yet)

For example, would be very handy when clicking "find all references" on a Greek/Hebrew dictionary definition if the result words would highlight

**Comment by agrogers** [comment]
Nope. But it is on my list to look at. That is probably the feature i most
want in this list.

These changes are very primitive. It should be replaced with the results
that come back from the Lucene queries but that needs some deep work
because it doesnt send back any info on the matches just the verse
references. But i think what I have there now would cover 95% of what most
people search for. Maybe more.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Just a quick comment for now: I would prefer this is implemented first: https://github.com/AndBible/and-bible/issues/611 because it changes how this needs to be implemented.

**Comment by agrogers** [comment]
611 is beyond my expertise at the moment. But I think there would still be
a place for the current simple search. Having become more familiar with our
users, I can see plenty of tickets coming through with 'what happened to
the old search - it was simple and this new one is too complicated'.

My thought had been that the simple search results list should remain with
the inclusion of a button at the top to open those results as document
window.

I think I would use both. Hard to know though until I have the new search
display in my hands.

**Comment by timbze** [comment]
Depends how soon or if someone is planning to work on #611, it might be a good idea to implement this for now. I agree that it's better than nothing, plus, it's already done. All that if the code is ok. I have not reviewed the code.

**Comment by tuomas2** [comment]
#611 is straightforward to implement, now that we have the "framework" in place. Not easy, requires knowing the current system of course, but nothing "new" there. It would be beneficial if someone else would do it as it would spread the knowledge. I am available for help. 

> 611 is beyond my expertise at the moment. But I think there would still be
> a place for the current simple search. Having become more familiar with our
> users, I can see plenty of tickets coming through with 'what happened to
> the old search - it was simple and this new one is too complicated'.

If I had that mindset I think I had to stop coding. I guess that's what certain users wish for sure. 
But that's not right attitude I think. Changes (that cause 1 star ratings from certain users) are 
necessary if we want to improve things.

That being said, if nobody is interested in taking the challenge of #611, this "old approach" can be 
acceptable too.

**Comment by agrogers** [comment]
This method has been superseded by https://github.com/AndBible/and-bible/pull/1953 
This one is a lot simpler and maybe faster since it doesn't have to process each word before applying the highlighting. Anyhow, I will close it in favour of the other.

**Pull request closed without merging**
