### PR TITLE
Study pad export 

### LINKED ISSUE #1328: export studypad in html, txt, even pdf if possible

### PR DESCRIPTION
**Pull request by tuomas2**
Closes #1328

### CODE REVIEW

**Comment by agrogers** [comment]
Look forward to seeing it.

**Comment by tuomas2** [comment]
ready on Thursday probably

**Comment by tuomas2** [comment]
Waiting for some help https://stackoverflow.com/questions/69750225/how-to-import-raw-css-as-raw-text-in-js-side-generated-from-vue-components

**Comment by tuomas2** [comment]
Screenshot_20211028_170344

**Comment by tuomas2** [comment]
Exporting kind of works but it does not have CSS yet, so it looks somewhat ugly.

**Comment by tuomas2** [comment]
feedback about this @AndBible/developers ?

**Comment by timbze** [comment]
I'm happy with the format, but would be nice to be able to copy as html (to paste in email etc), not sure if that's possible.

**Comment by tuomas2** [comment]
I agree. But already now it is easy to upload to Google Docs and Google Docs can be used even to edit the document.

**Comment by JJK96** [comment]
Looks fine to me, indeed a copy to clipboard would be nice-to-have, but this is a nice addition already!

**Pull request merged**
