### PR TITLE
Github actions release apk on build- tag

### PR DESCRIPTION
**Pull request by timbze**
**Describe the pull request content**
Whenever a tag is pushed that beings with build- , it will auto build and sign apk, create beta release and attach the apk.

**Requirements**
Repo secrets: 
JKS_BASE64 (create text with `openssl base64 -A -in keystorefile.jks`)
KEYSTORE_PASS
KEY_PASS

### CODE REVIEW

**Comment by tuomas2** [comment]
does apk go to github releases page?

**Comment by ildar** [comment]
line 42 and below: you should decide for yourself. This is fairly optional.

**Comment by tuomas2** [comment]
> line 42 and below: you should decide for yourself. This is fairly optional.

you  mean signing?

**Comment by ildar** [comment]
signing and further (uploading, etc.)

**Comment by tuomas2** [comment]
@timbze maybe next step would be use `fastlane supply` to release also on beta channel (perhaps with another tag prefix). And perhaps even to production with yet another tag...

**Comment by tuomas2** [comment]
In general this will save a lot of time from me in the long run (not having to upload manually to drive (and play store beta channel, later)). So thanks a lot! :-) 

Maybe we could make this conditional such that it does not release if tests fail (so chaining with another action somehow?).

**Comment by timbze** [comment]
> Maybe we could make this conditional such that it does not release if tests fail (so chaining with another action somehow?).

I would need to add it to my first PR. 

We can do it 2 ways:
1. With "if" conditions for the steps that are about release, to make sure if the push is a tag (added to #727 like this for now)
2. Add another job, for example, we have "build" job in the other file now. We could put the first job as "test", and add a second job "release" that would only run if push is a tag AND first job succeeded. However, each job has to set up everything, so that means quite a bit of the code would have to duplicate on job "release"

**Comment by timbze** [comment]
I think we should probably do it in only 1 file anyway for now. Closing this.

**Pull request closed without merging**
