### PR TITLE
Show the current verse reference in the window buttons

### PR DESCRIPTION
**Pull request by agrogers**
This replaces #2228

Sometimes I want to know the reference for other windows, especially when writing notes that refer to these verses. Amazingly I can forget that reference in a matter of seconds. This PR adds an option to show the reference in the button.

image

### CODE REVIEW

**Comment by tuomas2** [comment]
It's getting a bit crowded with all the info, but I agree this might be handy.

**Comment by tuomas2** [comment]
Let's see if one day we need to prioritize space usage with some other indicators :-P

**Comment by tuomas2** [comment]
Oops, forgot to review. Will create another PR for this and let's finish it there.

**Comment by agrogers** [comment]
I think it should be an Option, not mandatory.

**Pull request merged**
