### PR TITLE
Metadata for F-Droid

### PR DESCRIPTION
**Pull request by verdulo**
EO
Mi aldonis metadatumojn (fastlane) por F-Droid en Esperanto kaj pola lingvoj. Mi transsaltis la lastan frazon (“* projekt‑paĝo ĉe GitHub…”), ćar la ligilo al GitHub jam estas disponebla per F-Droid.

EN
I added metadata (fastlane) for F-Droid in Esperanto and Polish. I skipped the last sentence ("* project page on GitHub ..."), because the link to GitHub is already available with F-Droid.

### CODE REVIEW

**Comment by tuomas2** [comment]
Hmm we already are having this information in PlayStore/*/PlayStoreMainText.txt where info is coming directly from transifex. I think we need to change this, so that info is not duplicated.

**Comment by verdulo** [comment]
Ĉu eblas disigi la dosieron “PlayStoreShortText.txt” al du dosieroj: unu enhavanta nomon, alia enhavanta koncizan priskribon, kaj sekve krei simbolajn ligilojn?

Is it possible to separate the file "PlayStoreShortText.txt" into two files: one containing a name, another containing a concise description, and then creating symbolic links?

**Comment by verdulo** [comment]
EO
Bonvolu aldoni F-Droid-metadatumojn ANTAŬ eldoni la stabilan version.

FI
Lisää F-Droid-metatiedot ENNEN vakaan version julkaisua.

EN
Please add F-Droid metadata BEFORE releasing the stabile version.

**Comment by tuomas2** [comment]
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by tuomas2** [comment]
I fixed this by moving files to play/listings/, which another way supported by F-droid (https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/). I'm planning to start using gradle-play-publisher (https://github.com/Triple-T/gradle-play-publisher) that's why I chose that way. 

Closing this.

**Comment by tuomas2** [comment]
@verdulo it looks that unfortunately neither Play Store nor F-Droid support esperanto. Esperanto was included in 3.3.380 f-droid release, but it seems that it is not displayed in F-droid.

**Comment by verdulo** [comment]
Everything works:
bildo
https://staging.f-droid.org/eo/packages/net.bible.android.activity/

**Comment by tuomas2** [comment]
Oh, nice to know

**Pull request closed without merging**
