### PR TITLE
Replace the Refresh MenuItem in DownloadActivity with a SwipeRefreshLayout

### PR DESCRIPTION
**Pull request by uniqueid001**
#238: replace the refresh MenuItem with a SwipeRefreshLayout

### CODE REVIEW

**Comment by tuomas2** [comment]
I think we have reached a point when I would like to take only bugfixes to current-stable and focus everything else to develop. So changing target.

**Comment by tuomas2** [comment]
Did not try yet but SwipeRefreshLayout there sounds like a good idea!

**Review by tuomas2 — APPROVED** [review]

**Comment by tuomas2** [comment]
@uniqueid001 please check small code style improvements in the above mentioned commit

**Comment by uniqueid001** [comment]
> @uniqueid001 please check small code style improvements in the above mentioned commit

I see them.  
Many years ago I learned, from another project I worked with, to align the blocks (similar to Python).  Of course Kotlin's trailing lambda grammar doesn't allow aligning the opening brace, but I still habitually maintain the alignment of the closing brace.

**Pull request merged**
