### PR TITLE
Remember the last document type selected in the Documents list window

### PR DESCRIPTION
**Pull request by agrogers**
It has frustrated me when i go to the document selector that it always shows me every document. Now it remembers the previous selection.

### CODE REVIEW

**Comment by agrogers** [comment]
@tuomas2 , this fails a test that is not related to my code:
net.bible.android.control.page.window.WindowSynchronisationTest > testWindowSyncInMaxMode

**Comment by timbze** [comment]
@agrogers tests fail on develop branch, there is something that needs to be fixed. PRs will have same issue until that gets fixed

**Comment by agrogers** [comment]
> @agrogers tests fail on develop branch, there is something that needs to be fixed. PRs will have same issue until that gets fixed

Thanks Tim. I thought that must have been the case.

**Comment by tuomas2** [comment]
Looks ok to me, merging

**Pull request merged**
