### PR TITLE
Merge AppThemeDay and AppThemeNight into one DayNight theme

### LINKED ISSUE #621: System night mode switching broken
Night mode: "System" does not work (Android 10 feature, though some Samsung Android 9 also impelment it).

### LINKED ISSUE #630: Search view is opened twice
If a match appears a lot of times in the document, the search can take a lot of time.

For me, a search for "en" (Dutch for "and") in a Dutch translation yields more than 1000 results and takes about 23 seconds on my device.

My device is a OnePlus 6 with Android 10.

### PR DESCRIPTION
**Pull request by JJK96**
Please test this thoroughly on your devices before merging.

Also ping me if you want to merge so I can squash the commits, these commit messages are not production ready.

Fixes #621 and fixes #630

### CODE REVIEW

**Comment by JJK96** [comment]
Speak view, `-stopped-` text is white on white.

**Comment by tuomas2** [comment]
If this requires a lot of testing and has possibility of breaking things greatly, I want to postpone this to past-release time.

**Comment by JJK96** [comment]
That sounds like a good idea

**Comment by tuomas2** [comment]
Testing on emulator running Android 10.
Bugs:
 - [ ] In day mode, navigation bar color wrong on other than main activity

**Comment by JJK96** [comment]
The color of the navigation bar is different from the old theme, but do you mean that the color changes when you open another activity? 
Do you have screenshots, since for me the navigation bar color is the same for every activity.

**Comment by tuomas2** [comment]
Here are screenshots:
Should look like this:
Screenshot_1592476989

Looks like this:
Screenshot_1592476863

You can try yourself in emultator (Android 10, API 29) too (old code vs new code).

**Comment by JJK96** [comment]
Your screenshots show the same color that I see. 
I removed some of the custom colors and found that the default android colors looked fine (to me), so this would simplify the theme a bit.

Do you disagree?
Do you want the colors to be exactly the same as the current theme?

**Comment by timbze** [comment]
Android 8.0 on LG G6 does not show everything correctly in night mode. See pics:
Edit: I removed most pics now because I longer have that issue. Not sure why I had them before.

This issue remains: reference color in fullscreen here has gotten an odd color:
image

**Comment by timbze** [comment]
I think I have now fixed the rest of issues mentioned in the comments.

0df6fc9 is about a separator line in dark theme that looks bad (or distracting) to me (also was mentioned in AB Support group on June 11)

**Comment by tuomas2** [comment]
Okay, let's continue testing in develop :-)

**Pull request merged**
