### PR TITLE
F-droid fixes

### PR DESCRIPTION
**Pull request by tuomas2**
Related #2945

Remove non-free stuff (google drive related) from F-droid build

### CODE REVIEW

**Comment by tuomas2** [comment]
Still build fails for F-droid build because GoogleDriveCloudAdapter.kt is built (even though it is not used). Should somehow exclude that from being built.

**Comment by ildar** [comment]
Thanks for fixing this! F-Droid becomes even more important these days.

**Comment by tuomas2** [comment]
It's just pity that Google Drive support can't be enabled in F-droid build.

**Comment by ildar** [comment]
On Thu, Nov 2, 2023 at 3:41 PM Tuomas Airaksinen wrote:

> It's just pity that Google Drive support can't be enabled in F-droid build.
>
It may be convenient but not essential after all.
thanks!

**Comment by tuomas2** [comment]
#2615  will fix that

**Pull request merged**
